First nibble at an iOS client.
This doesn't fully work yet. It connects, then explodes in IOSIO.findStreamer:

WARN: Error writing network data [msg=com.threerings.nexus.net.Upstream$Subscribe@889eb300]
cli.System.InvalidOperationException: Only support ICustomInvoke ctor accessors in no-emit mode.
	at IKVM.NativeCode.sun.reflect.ReflectionFactory.newConstructorAccessor0(openjdk.cs:7822)
	at sun.reflect.ReflectionFactory.newConstructorAccessor0(Native Method)
	at sun.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:133)
	at java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:565)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:517)
	at java.lang.Class.newInstance0(Class.java:438)
	at java.lang.Class.newInstance(Class.java:425)
	at com.threerings.nexus.io.IOSIO.findStreamer(IOSIO.java:395)
	at com.threerings.nexus.net.IOSConnection$Writer.run(IOSConnection.java:207)

Assuming reflection works in IKVM, I'm not sure what's going wrong. @samskivert?